name: Build and Deploy to S3

on:
  push:
    branches:
      - main  # 或你想要触发构建的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # 使用你需要的 Java 版本
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package  # 或使用你的构建工具
        
      - name: Upload JAR to S3
        run: |
          aws s3 cp target/demo-0.0.1-SNAPSHOT.jar s3://${{ secrets.S3_BUCKET4SPRINGBOOT }}/demo-0.0.1-SNAPSHOT.jar
      # - name: Upload to S3
      #   uses: jakejarvis/s3-sync-action@master
      #   with:
      #     args: --acl public-read --cache-control "max-age=31536000"
      #     bucket: ${{ secrets.AWS_S3_BUCKET }}
      #     file: target/demo-0.0.1-SNAPSHOT.jar  # 修改为你的 JAR 文件路径
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: ${{ secrets.AWS_REGION }}
