name: Build and Send to S3 and Deploy to EC2

on:
  push:
    branches:
      - main  # 或你想要触发构建的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # 使用你需要的 Java 版本
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package  # 或使用你的构建工具
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  
          
      - name: Upload JAR to S3
        run: |
          aws s3 cp target/demo-0.0.1-SNAPSHOT.jar s3://${{ secrets.S3_BUCKET4SPRINGBOOT }}/demo-0.0.1-SNAPSHOT.jar
      
      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_SSH_KEY" > private_key.pem
          chmod 400 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'

            # sudo apt update -y
            # sudo apt install openjdk-17-jdk -y -qq
            sudo yum update -y
            sudo yum install java-17-amazon-corretto -y
            
            # # 安装 AWS CLI（若未安装）
            # sudo apt install awscli -y -qq
            
            # # 配置 AWS 凭据（临时）
            # aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            # aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            # aws configure set region ${{ secrets.AWS_REGION }}

            cd /home/springboot
            # 下载 JAR
            aws s3 cp s3://${{ secrets.S3_BUCKET4SPRINGBOOT }}/demo-0.0.1-SNAPSHOT.jar .
            
            # 停止现有进程（可选）
            sudo pkill -f 'java -jar' || true
            
            # 运行 JAR, 80 端口是特权端口（<1024），非 root 用户无法绑定，需要 sudo。
            sudo nohup java -jar demo-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
            # java -jar demo-0.0.1-SNAPSHOT.jar -ccc="c from cmd"
          EOF
